#! /usr/bin/env bash

export PATH="${ASDF_DATA_DIR:-/home/cjpoll/.asdf}/shims:/home/cjpoll/bin/:$PATH"
cd ~/dev/widgets
echo $(ruby --version) > logs/ruby-version.log
bundle exec ruby widgets.rb "${@}"
